### ISSUE TITLE
crash if ip is unreachable

### ISSUE THREAD

**Issue by cbrandlehner** [PeteLawrence/homebridge-people#1]
When using an IP address which is available on the local network I had success using homebridge-people.
However if the IP address is not reachable the plugin crashes. This is the log:
Homebridge is running on port 51826.
28 Feb 12:14:27 - [JsonDB] DataBase seen.db.json loaded.

/usr/lib/node_modules/homebridge-people/node_modules/node-json-db/JsonDB.js:94
                    throw new DataError("Can't find dataPath: /" + dataPath.jo
                          ^
NestedError: Can't find dataPath: /192.168.1.78. Stopped at 192.168.1.78
    at DataError.Error (native)
    at DataError.NestedError (/usr/lib/node_modules/homebridge-people/node_modules/node-json-db/lib/Errors.js:7:25)
    at new DataError (/usr/lib/node_modules/homebridge-people/node_modules/node-json-db/lib/Errors.js:37:33)
    at findData (/usr/lib/node_modules/homebridge-people/node_modules/node-json-db/JsonDB.js:94:27)
    at recursiveProcessDataPath (/usr/lib/node_modules/homebridge-people/node_modules/node-json-db/JsonDB.js:120:17)
    at JsonDB._getData (/usr/lib/node_modules/homebridge-people/node_modules/node-json-db/JsonDB.js:133:16)
    at JsonDB.getData (/usr/lib/node_modules/homebridge-people/node_modules/node-json-db/JsonDB.js:64:21)
    at PeopleAccessory.getState (/usr/lib/node_modules/homebridge-people/index.js:39:33)
    at emit (events.js:110:17)
    at Characteristic.getValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:120:10)

**Comment by PeteLawrence** [comment]
Thanks for reporting this, if you ```npm install -g homebridge-people``` again it should give you the fixed version.
