### ISSUE TITLE
Crashing since Update

### ISSUE THREAD

**Issue by samsonrosen** [PeteLawrence/homebridge-people#48]
Hello,

I've updated the plugin and adjusted my config to the platform, but now Homebridge keeps crashing.

Have I entered something incorrectly? I took the People config out and the plugin started fine.
[config.json.zip](https://github.com/PeteLawrence/homebridge-people/files/691431/config.json.zip)

```
{
   "bridge":{
      "name":"Homebridge",
      "username":"CC:22:3D:E3:CE:30",
      "port":51826,
      "pin":"031-45-154"
   },
   "description":"Homebridge",
   "accessories":[
      {
         "accessory":"WeMo",
         "name":"HP Printer",
         "wemo_name":"WeMo Switch"
      }
   ],
   "platforms":[
      {
         "platform":"Camera-ffmpeg",
         "cameras":[
            {
               "name":"Room",
               "videoConfig":{
                  "source":"-re -f avfoundation -framerate 30 -video_size 1280x720 -i 0:0",
                  "maxStreams":2,
                  "maxWidth":1280,
                  "maxHeight":720,
                  "maxFPS":30
               }
            }
         ]
      },
      [
         {
            "platform":"People",
            "threshold":15,
            "anyoneSensor":true,
            "nooneSensor":true,
            "webhookPort":51828,
            "cacheDirectory":"./.node-persist/storage",
            "pingInterval":10000,
            "ignoreReEnterExitSeconds":0,
            "people":[
               {
                  "name":"Alvin",
                  "target":"192.168.1.86",
                  "threshold":15,
                  "pingInterval":10000,
                  "ignoreReEnterExitSeconds":0
               },
               {
                  "name":"Simon",
                  "target":"192.168.1.217",
                  "threshold":15,
                  "pingInterval":10000,
                  "ignoreReEnterExitSeconds":0
               },
               {
                  "name":"Theodore",
                  "target":"192.168.1.125",
                  "threshold":15,
                  "pingInterval":10000,
                  "ignoreReEnterExitSeconds":0
               },
               {
                  "name":"Chipmunk",
                  "target":"192.168.1.115",
                  "threshold":15,
                  "pingInterval":10000,
                  "ignoreReEnterExitSeconds":0
               }
            ]
         },
         {
            "platform":"cmdSwitch2",
            "switches":[
               {
                  "name":"Kettle",
                  "on_cmd":"/Users/churchserver/iBrew/ibrewlegacy heat 192.168.1.5",
                  "off_cmd":"/Users/churchserver/iBrew/ibrewlegacy stop 192.168.1.5",
                  "state_cmd":"/Users/churchserver/iBrew/ibrewlegacy status 192.168.1.5 | grep 'Heating water 100ºC selected'",
                  "polling":true,
                  "interval":10
               },
               {
                  "name":"TV",
                  "on_cmd":"python /Users/churchserver/python-broadlink/BlackBeanControl/BlackBeanControl.py -c PowerToshiba"
               },
               {
                  "name":"Amp",
                  "on_cmd":"python /Users/churchserver/python-broadlink/BlackBeanControl/BlackBeanControl.py -c PowerAmplifier"
               },
               {
                  "name":"Mute TV",
                  "on_cmd":"python /Users/churchserver/python-broadlink/BlackBeanControl/BlackBeanControl.py -c MuteTV"
               },
               {
                  "name":"Mute Amp",
                  "on_cmd":"python /Users/churchserver/python-broadlink/BlackBeanControl/BlackBeanControl.py -c MuteAmp"
               }
            ]
         }
      ]
   ]
}
```

This is the error log:

```
Church-Server:~ churchserver$ homebridge 
[1/7/2017, 10:38:29 AM] Loaded plugin: homebridge-camera-ffmpeg
[1/7/2017, 10:38:29 AM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[1/7/2017, 10:38:29 AM] ---
[1/7/2017, 10:38:29 AM] Loaded plugin: homebridge-cmdswitch2
[1/7/2017, 10:38:29 AM] Registering platform 'homebridge-cmdswitch2.cmdSwitch2'
[1/7/2017, 10:38:29 AM] ---
[1/7/2017, 10:38:29 AM] Loaded plugin: homebridge-milight
[1/7/2017, 10:38:29 AM] Registering platform 'homebridge-milight.MiLight'
[1/7/2017, 10:38:29 AM] ---
[1/7/2017, 10:38:29 AM] Loaded plugin: homebridge-people
[1/7/2017, 10:38:29 AM] Registering platform 'homebridge-people.People'
[1/7/2017, 10:38:29 AM] Registering accessory 'homebridge-people.PeopleAccessory'
[1/7/2017, 10:38:29 AM] Registering accessory 'homebridge-people.PeopleAllAccessory'
[1/7/2017, 10:38:29 AM] ---
[1/7/2017, 10:38:29 AM] Loaded plugin: homebridge-wemo
[1/7/2017, 10:38:29 AM] Registering accessory 'homebridge-wemo.WeMo'
[1/7/2017, 10:38:29 AM] ---
[1/7/2017, 10:38:29 AM] Loaded config.json with 1 accessories and 2 platforms.
[1/7/2017, 10:38:29 AM] ---
[1/7/2017, 10:38:29 AM] Loading 2 platforms...
[1/7/2017, 10:38:29 AM] Initializing Camera-ffmpeg platform...
/usr/local/lib/node_modules/homebridge/lib/api.js:104
  if (name.indexOf('.') == -1) {
          ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:104:11)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:284:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:80:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
Church-Server:~ churchserver$
```

**Comment by benzman81** [comment]
Yes, the square bracket right before the people platform is wrong.

**Comment by samsonrosen** [comment]
Simple fix!

Thank you so much.
