### ISSUE TITLE
ERROR on Load

### ISSUE THREAD

**Issue by theo-69** [PeteLawrence/homebridge-people#93]
Since yesterday I am getting this error if i restart homebridge:
`Server error: Error: listen EADDRINUSE :::8282
Error: listen EADDRINUSE :::51828
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1406:7)
    at PeoplePlatform.startServer (/usr/lib/node_modules/homebridge-people/index.js:120:24)
    at PeoplePlatform.accessories (/usr/lib/node_modules/homebridge-people/index.js:60:14)
    at Server._loadPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:364:20)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:308:16)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
`
If I restart the complete PI it is working...

**Comment by xdenneboom** [comment]
yeah, I'm also getting this now. any luck?
